name: push

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.5
    - name: Build
      run: |
        echo "[INFO]: Building"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_PACKAGE_TOKEN }}
  release:
      name: Release
      needs: build
      runs-on: ubuntu-18.04
      steps:
        - name: Checkout
          uses: actions/checkout@v2.3.5
        - name: Setup Node.js
          uses: actions/setup-node@v2.2.0
          with:
            node-version: 14
        - name: Release
          env:
            GITHUB_TOKEN: ${{ secrets.GHTOKEN }}
          run: npx semantic-release@17
